const sidebars = {
  tutorialSidebar: [
    'README',
    {
      type: 'category',
      label: 'Use Case Building Blocks',
      link: {
        type: 'doc',
        id: 'use-cases/README',
      },
      items: [
        // Core Use Cases
        {
          type: 'category',
          label: 'Document Processing',
          link: {
            type: 'doc',
            id: 'use-cases/document-processing/README',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'use-cases/document-processing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Web Application',
          link: {
            type: 'doc',
            id: 'use-cases/webapp/README',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'use-cases/webapp',
            },
          ],
        },
        // Framework
        {
          type: 'category',
          label: 'Framework',
          items: [
            {
              type: 'autogenerated',
              dirName: 'use-cases/framework',
            },
          ],
        },
        // Utilities
        {
          type: 'category',
          label: 'Utilities',
          link: {
            type: 'doc',
            id: 'use-cases/utilities/README',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'use-cases/utilities',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Ready-to-Deploy Examples',
      link: {
        type: 'doc',
        id: 'examples/README',
      },
      items: [
        {
          type: 'category',
          label: 'Document Processing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'examples/document-processing',
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
