import { Grant, IGrantable, IRole, PolicyStatement } from 'aws-cdk-lib/aws-iam';
import { ILogGroup } from 'aws-cdk-lib/aws-logs';
import { AgentRuntimeType } from './types';

/**
 * Abstract interface for runtime-specific implementations
 *
 * This interface provides a unified abstraction over different agent runtime types
 * (Lambda and AgentCore), enabling the framework to work with either runtime
 * through a consistent API.
 *
 * Implementations of this interface handle runtime-specific details such as:
 * - IAM role configuration with appropriate service principals
 * - Invocation mechanisms and ARN formats
 * - Environment variable management
 * - Permission grants for invoking the agent
 * - CloudWatch log group configuration
 */
export interface IAgentRuntime {
  /**
   * The type of runtime (Lambda or AgentCore)
   *
   * Used for runtime-specific logic without instanceof checks.
   * This enables type-safe branching based on runtime capabilities.
   */
  readonly runtimeType: AgentRuntimeType;

  /**
   * The IAM execution role for the agent
   *
   * This role is assumed by the runtime service (Lambda or AgentCore) when
   * executing the agent code. It should have permissions to:
   * - Invoke Bedrock models
   * - Access tool assets in S3
   * - Write to CloudWatch Logs
   * - Access any other AWS resources required by the agent
   *
   * The service principal of this role differs by runtime type:
   * - Lambda: lambda.amazonaws.com
   * - AgentCore: agentcore.amazonaws.com
   */
  readonly executionRole: IRole;

  /**
   * The ARN or identifier for invoking the agent
   *
   * This is the resource identifier used when granting invocation permissions
   * or invoking the agent from other AWS services.
   *
   * Format differs by runtime type:
   * - Lambda: arn:aws:lambda:region:account:function:function-name
   * - AgentCore: arn:aws:bedrock-agentcore:region:account:agent-runtime/runtime-id
   */
  readonly invocationArn: string;

  /**
   * The CloudWatch log group for this agent
   *
   * Contains logs generated by the agent during execution. May be undefined
   * if logging is not configured or not yet created.
   *
   * Log group naming differs by runtime type:
   * - Lambda: /aws/lambda/function-name
   * - AgentCore: /aws/bedrock-agentcore/runtimes/runtime-name
   */
  readonly logGroup?: ILogGroup;

  /**
   * Grant permission to invoke this agent
   *
   * Adds the appropriate IAM permissions to the grantee to allow invocation
   * of this agent. The specific permissions granted depend on the runtime type:
   * - Lambda: lambda:InvokeFunction
   * - AgentCore: bedrock-agentcore:InvokeAgentRuntime
   *
   * @param grantee The principal to grant invocation permissions to
   * @returns Grant object representing the permission grant
   */
  grantInvoke(grantee: IGrantable): Grant;

  /**
   * Configure environment variables for the agent
   *
   * Environment variables are made available to the agent code at runtime.
   * The mechanism for setting environment variables differs by runtime type,
   * but this interface provides a consistent API.
   *
   * Common use cases:
   * - Model configuration (MODEL_ID, TEMPERATURE)
   * - S3 bucket names and keys for tools and prompts
   * - Feature flags and behavior toggles
   * - Observability configuration (POWERTOOLS_*, OTEL_*)
   *
   * @param key The environment variable name
   * @param value The environment variable value
   */
  addEnvironment(key: string, value: string): void;

  /**
   * Add IAM policy statements to the execution role
   *
   * Grants the agent's execution role additional permissions to access AWS
   * resources. This is commonly used to:
   * - Grant access to S3 buckets containing tools or data
   * - Grant permissions to invoke other AWS services
   * - Grant access to DynamoDB tables, SQS queues, etc.
   *
   * The policy statement is added to the execution role's inline policy,
   * regardless of runtime type.
   *
   * @param statement The IAM policy statement to add
   */
  addToRolePolicy(statement: PolicyStatement): void;
}
